### ISSUE TITLE
Saving in place does not work on Google Chrome Version 58.0.3029.81 (64-bit)

### ISSUE THREAD

**Issue by edendekker** [Arlen22/tiddly-chrome-app#14]
I have tested out version 0.6 release on chrome version 58.0.3029.81 (64-bit)
When i click the save button, it downloads it as a new file.
I am unsure if this issues occurs in master.
I am using Ubuntu Desktop 15.04.

**Comment by Arlen22** [comment]
Please check if this is the problem: https://github.com/Arlen22/tiddly-chrome-app/issues/6

**Comment by edendekker** [comment]
Yes it does help, thank you! :)
