### ISSUE TITLE
Unable to edit any longer

### ISSUE THREAD

**Issue by gmcbrien** [Arlen22/tiddly-chrome-app#18]
Hello, I would hate to lose Tiddlywiki :-( but currently I'm unable to edit it in Chrome any longer as it's not displaying properly -  I now only see a small 'sliver' at the top.

To be fair, it has been like this for several months, thinking I would have resolved it by now. But apparently not.

Please refer to the screenshot. BTW - this happens on multiple instances of Chrome (in office, on laptop, at home etc).
Any help appreciated, thanks.

![Screenshot_3](https://user-images.githubusercontent.com/31663967/55184619-e7f24480-5192-11e9-8a48-7ef4e9cb7186.jpg)

**Comment by Arlen22** [comment]
Google Chrome Apps are supposed to be going away, so I haven't been making this a priority. I will keep it in mind.

**Comment by gmcbrien** [comment]
Sorry for the late response. Then the question remains, how can I use my Tiddlywiki? Viewing is no problem at all, but of course I would like to add to my TW, but seem to have no possibilities. Is there any working solution out there, would you know?
Thanks a lot

**Comment by Arlen22** [comment]
It seems to be back, as other users currently seem to be able to use this app.
