### ISSUE TITLE
Always saves a new file

### ISSUE THREAD

**Issue by gmcbrien** [Arlen22/tiddly-chrome-app#20]
Hi, I am SO missing my Tiddlywiki :-( 
So, the plugin works generally OK. But, after I commit any changes (by pressing the red 'tick') it wants to save a new version of the file - e.g. empty (1).html... then empty (1) (1).html and so on.

Is this expected behaviour?

Thanks a lot

**Comment by Arlen22** [comment]
Are you opening it in the app or just in a regular browser tab? This is a chrome app which you open from chrome://apps

**Comment by gmcbrien** [comment]
Thanks for the fast response. I am familiar with Tiddlywiki / Tiddlychrome, and I normally us it via the Chrome Apps. Maybe today I made a mistake. However, what's exciting is that I basically started again, installed latest version 0.7 and it seems to be working fine. This is very exciting :-)

Thanks a lot for all your efforts and great support.

**Comment by gmcbrien** [comment]
Just one additional note - the version in Github shows 0.7, as does the corresponding zip file name, but the version in Chrome extensions still shows 0.6 (I did a clean installation just now). I manually updated your manifest.json though and re-installed :)
