### ISSUE TITLE
General TW question, if I may ask here

### ISSUE THREAD

**Issue by DBJDBJ** [Arlen22/tiddly-chrome-app#21]
AS far as I can see if I run empty.html (aka tiddly wiki) through a web server, it will save itself properly etc? 
Will, it just keep on changing this empty.html or will it add files to the same folders?  How and where it will keep the images?

Thank you for your time.

ps: I can run it from inside VS Code with the help of a local web server extension. But it just produces new copies of empty.html ...

**Comment by Arlen22** [comment]
Yes, it will just keep changing it. If VS Code is making new copies, then it's probably using the download mechanism instead. Try comparing the reqests in the network tab to one in a chrome window. 

TiddlyServer has a backup feature which will save backups to a separate folder. See https://arlen22.github.io/tiddlyserver/docs/serverconfig.html#section-putsaver

**Comment by DBJDBJ** [comment]
well, it seems there is some fundamental step one I have not done or doing it wrong :)  whichever way I try to save is either local file system or I have 404 from a Github? 

I can see it (same as you, I assume) https://dbjdbj.github.io/tw/ ... but "nothing works" as far as saving goes? yes I know about Github API keys etc ... I have made a new one. I click the "saving tick"  but 404 is coming back after half a minute?

**Comment by Arlen22** [comment]
Oops, for some reason I thought this was on the TiddlyServer repo. 

You're using this app in VS code? I guess if it works it works, but it's built on Electron, so I don't know how that would work. 

TiddlyChromeApp is meant to open a file on disk and then save it in place. I don't know whether it can create new copies or not. Either way, you need to make sure you're opening the file when you run the app, opening it in a browser tab is not enough.

**Comment by DBJDBJ** [comment]
I am trying to make it work on Github .... forget VS Code L)

**Comment by Arlen22** [comment]
TiddlyChromeApp is only designed to work with the local file system, and TiddlyWiki only saves to the first saver that does so successfully, so if it saves to the file system it won't save to GitHub. You can access the dev tools for the different frames at `chrome://inspect/#apps`, and you should be able to inspect the $tw global from there to see what's going on, as well as network requests.

**Comment by DBJDBJ** [comment]
OK thanks I was trying for advice without your Chrome extension. :)

**Comment by Arlen22** [comment]
You'll get more help on the TiddlyWiki Google Group. It's pretty active :)

**Comment by DBJDBJ** [comment]
When and if TW might not require development effort to be able to use it, I might use it then ...

**Comment by Arlen22** [comment]
TiddlyWiki is certainly a bit of a blank canvas. I'm sure there are other solutions, like OneNote and Google Keep. The TiddlyWiki forum is very active so I definitely recommend that you post your questions there as I only focus on one part of it. However, if you already did and didn't get much help, if you post a link to it here I can take a look and see if I can help.

**Comment by DBJDBJ** [comment]
Well thank you for that ... it is really rather simple and might take 15 min to prove or disapprove.

https://dbjdbj.github.io/tw/

if you have time I can make you a "team member " on that one ... I think.

That URL is a folder of the organization's site. A bit convoluted but why not ... that should work.  
Repo is https://github.com/DBJDBJ/dbjdbj.github.io

Thus I dutifully do this setup:

![image](https://user-images.githubusercontent.com/145155/115999970-8e1d0c80-a5ee-11eb-8d6d-7298489be6bc.png)

and after approx 30 sec I get

![image](https://user-images.githubusercontent.com/145155/116000008-bd337e00-a5ee-11eb-9a58-ddf6627e527a.png)

Yes I tried with a token and I tried with a password. That account is under 2FA maybe that is a problem? 

Please advise ...

**Comment by DBJDBJ** [comment]
It seems the issue is a toxic combination of assumptions on behalf of the TW team AND the GitHub pages team.

they perhaps just assume everybody knows about critical details, like for example where is the repo for the above URL?

It certainly is not at https://github.com/dbjdbj/tw ? I have a repo localy under the git and git remote -v tells me

```
origin  https://github.com/DBJDBJ/tw.git (fetch)
origin  https://github.com/DBJDBJ/tw.git (push) 
```

But it seems ther is no repo there as github comes back with 404 on that one?

**Comment by DBJDBJ** [comment]
F12 reveals problems

![image](https://user-images.githubusercontent.com/145155/116000221-97f33f80-a5ef-11eb-9962-3f505e183ae9.png)


And this is where one need to become a TW developer in order to save the issues it seems

**Comment by DBJDBJ** [comment]
If I switch of automatic save I can se that correct HTTP is attempted

![image](https://user-images.githubusercontent.com/145155/116000381-3f707200-a5f0-11eb-8be2-ee39839cacf1.png)

but both URLS have this `content` part ? 

https://api.github.com/repos/dbjdbj.github.io/contents/tw/index.html

and so on ...

**Comment by DBJDBJ** [comment]
If I change the repo to the probably more correct `dbjdbj/dbjdbj.github.io` the outcome is the same

![image](https://user-images.githubusercontent.com/145155/116000734-af332c80-a5f1-11eb-8c44-ea395fea2aa1.png)

**Comment by Arlen22** [comment]
`https://github.com/DBJDBJ/dbjdbj.github.io/tree/master/tw` is the location of that TiddlyWiki. 

It appears that https://docs.github.com/en/rest/reference/repos#create-or-update-file-contents is the command you need to run to do the update. 

I ran a quick test on my account and it appears that your settings should look like this. Of course you need to make sure the username and access key are set as well. I don't really know where these get saved or how this is supposed to look for a publicly hosted wiki. 

Settings | value
-- | --
Target repository (e.g. Jermolene/TiddlyWiki5) |  DBJDBJ/dbjdbj.github.io
Target branch for saving |  master
Path to target file (e.g. /wiki/) |  /tw/
Filename of target file (e.g. index.html) |  index.html
Server API URL | https://api.github.com

However, I'm suspicious of that `?ref=main` call. That appears to be a bug, because if I change it to master on my repo it works correctly, and it appears that your case would be the same.

**Comment by Arlen22** [comment]
The password is saved in localstorage. So if you are on a public site like your user page repo, then it's fine to leave the other values saved in the public form because all of those values can be guessed directly from the page URL, since there are only either user or project github.io pages anyway.

**Comment by Arlen22** [comment]
Ok, to fix the branch problem, just edit the branch field in the github settings so that the `$:/Github/Branch` tiddler gets created. You can set it back to the same value (`master`), but you need to type in the field so it actually get's created and saved. This actually is a bug, so I'll open a bug report for that part.

**Comment by Arlen22** [comment]
Actually I see you already opened a bug report at https://github.com/Jermolene/TiddlyWiki5/issues/5637

**Comment by Arlen22** [comment]
After working around the branch bug, it appears to be working for me.

**Comment by DBJDBJ** [comment]
And it worketh for me too.  Thanks :)

What is peculiar after 10+ years TW is in some sort of (pre)alpha stage ...?

**Comment by Arlen22** [comment]
Not necessarily. TiddlyWiki is actually built as a sort of blank canvas for people to design systems with, although for simply organizing notes it's pretty much all there. Most of the improvements usually focus around widgets and filters; and performance enhancements. There are some edges that we're still working on getting figured out but I would say it's been stable for about five years. There have been some under the hood adjustments which I and others have been working on as well to get some of the server-client things more optimized. 

That being said, we don't have tests for everything, although we would like to. And some things, like this particular bug, are hard to catch if you don't have a lot of people using that particular feature.
