### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by xenogenesi** [Arlen22/tiddly-chrome-app#6]
`Version 52.0.2743.116 built on Debian stretch/sid, running on Debian stretch/sid (64-bit)`

`TiddlyWiki 5.1.13`

The extension is installed and enabled but doesn't seem to work, a popup appear on top-right of the window saying `saved`, but _chromium_ still save  (or ask to save, depending on settings) a new file with an incremental suffix (eg: `empty (1).html`)

**Comment by Arlen22** [comment]
This is a chrome app. Usually you can open it from chrome://apps. If you just open a TiddlyWiki in a new tab it won't work. Let me know whether or not this solves your problem.

**Comment by xenogenesi** [comment]
Thank you very much @Arlen22, it works!
I never used a chrome app before, you should add a note in the readme.
