### ISSUE TITLE
App broken in Chrome 53

### ISSUE THREAD

**Issue by bram85** [Arlen22/tiddly-chrome-app#7]
Just updated to Chrome 53.0.2785.143 m (64-bit), and now the app has stopped working.

When I load the app, I get the Open dialog to select my TiddlyWiki file. When I select it, I get a blank page. The top bar with the Reload/Load buttons is still visible. The same file opens properly in a normal Chrome tab.

When I inspect _window.htm_, I see:

`<webview>: The load has aborted with error -3: ERR_ABORTED.`

Already tried to re-install the app, but that didn't fix it for me.

**Comment by Arlen22** [comment]
I am getting the same problem. Do you know when the last time was that it worked for you?

**Comment by bram85** [comment]
It worked for me on the day I reported this issue, coming from version 52.0.2743.116. I'm using the stable channel.

Things I tried:
- Tried with an pristine TiddlyWiki (empty.html) from the site. Same result.
- Enabled/disabled/changed CSS properties of the webview. I got a clue after some Googling that it could have something to do with a zero surface of the view.
- Look up the call stack when the message appears in the console. Still no clue where the event comes from.

**Comment by Arlen22** [comment]
Interesting. The funny thing is that a regular website works fine. Only a blob URL does not seem to work anymore. I've opened a bug report for Chrome. We'll see once what happens. Im hoping it is a temporary bug that will get addressed in the next update.

**Comment by Arlen22** [comment]
If anyone is interested, the bug report is at https://bugs.chromium.org/p/chromium/issues/detail?id=654629

**Comment by bram85** [comment]
Thanks, I'll keep an eye on the bug report as well.

**Comment by Arlen22** [comment]
It appears to be fixed in Chrome 54. Can you verify this for you?

**Comment by bram85** [comment]
Yup, confirmed. Thanks for the help.
