### ISSUE TITLE
Encrypted tiddlywikis with TiddlyChrome?

### ISSUE THREAD

**Issue by willwray** [Arlen22/tiddly-chrome-app#8]
I get  an error box when opening an [encrypted tiddlywiki](http://tiddlywiki.com/#Encryption) with the TiddlyChrome app: 

> TiddlyChrome could not add the saver. It cannot save any changes.... (truncated)

If I open a regular tiddlywiki in TiddlyChrome and add a password, then it saves encrypted ok while open but quitting the app and reopening gives the same error as above.

TiddlyFox appears to work ok for opening, saving and reopening encrypted tiddlywikis.

Can TiddlyChrome be made to work with encrypted tiddlywikis?

**Comment by Arlen22** [comment]
Yes, first make sure you are using the latest version. I will look into it.

**Comment by Arlen22** [comment]
https://github.com/Arlen22/tiddly-chrome-app/releases/tag/0.6

Here you go. Install it the usual way.
