### ISSUE TITLE
Automatically open a default wiki

### ISSUE THREAD

**Issue by superxiao** [Arlen22/tiddly-chrome-app#9]
The app is awesome! Thank you for making saving so easy.
Is it possible to assign a default wiki file so that it is opened automatically when tiddlychrome is opened?

**Comment by Arlen22** [comment]
You cannot set a default file, but if you open chrome://apps and right-click on the app, you can make a desktop shortcut. Then you can drag a file onto the shortcut to open it or add it as an argument to the shortcut.

**Comment by superxiao** [comment]
Thank you! It is just what I want.
